# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('beds', models.IntegerField()),
            ],
            options={
                'ordering': ['-beds'],
            },
        ),
    ]
