# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_hospitalbeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('user_rating', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hospital Rating',
                'verbose_name_plural': 'Hospital Ratings',
            },
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['-avg_rating'], 'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='hospitalbeds',
            options={'ordering': ['is_bed_available'], 'verbose_name': 'Hospital Bed', 'verbose_name_plural': 'Hospital Beds'},
        ),
        migrations.AddField(
            model_name='hospitalrating',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Hospital'),
        ),
    ]
