# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20170904_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(max_length=2)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Hospital')),
            ],
            options={
                'verbose_name': 'Hospital Booking',
                'verbose_name_plural': 'Hospital Bookings',
            },
        ),
    ]
