# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_hospitalbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='disease_speciality',
            field=models.CharField(default='0.00', max_length=200),
            preserve_default=False,
        ),
    ]
