# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_hospital_disease_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='disease_speciality',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
